applicationInfo:
  environmentId: development

across:
  development:
    active: true

spring:
  datasource:
    url: jdbc:h2:../db/my-application-db
    username: sa

  devtools:
    restart:
      additional-paths: src/main/resources
      additional-exclude: "messages/**,views/**"